{
    "status": "failed", 
    "name": "test_nested_steps_inside_test[True-True-True]", 
    "parameters": [
        {
            "name": "first_fail_before_second", 
            "value": "True"
        }, 
        {
            "name": "first_fail_after_second", 
            "value": "True"
        }, 
        {
            "name": "second_fail", 
            "value": "True"
        }
    ], 
    "parentIds": [], 
    "labels": [
        {
            "name": "testClass", 
            "value": "test.steps.nested_steps_test"
        }
    ], 
    "stop": 1482258280511, 
    "statusDetails": {
        "message": "AssertionError: assert not True", 
        "trace": "first_fail_before_second = True, first_fail_after_second = True, second_fail = True\n\n    @pytest.mark.parametrize(\"first_fail_before_second, first_fail_after_second, second_fail\", fruit_machine)\n    def test_nested_steps_inside_test(first_fail_before_second, first_fail_after_second, second_fail):\n        with pytest.allure.step('First step'):\n>           assert not first_fail_before_second\nE           assert not True\n\ntest/steps/nested_steps_test.py:65: AssertionError"
    }, 
    "start": 1482258280510, 
    "steps": [
        {
            "name": "First step", 
            "description": null, 
            "descriptionHtml": null, 
            "steps": null, 
            "attachments": null, 
            "start": 1482258280511, 
            "stop": 1482258280511, 
            "id": null, 
            "status": "failed", 
            "statusDetails": null, 
            "parameters": null
        }
    ], 
    "fullName": "test.steps.nested_steps_test#test_nested_steps_inside_test[True-True-True]", 
    "afters": [], 
    "id": "d671fc33711a1e5a45ea6f6fd77a22dc", 
    "befores": []
}