<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1412949538851" stop="1412949560112" version="1.4.4-SNAPSHOT">
    <name>my.company.ManyInfoTest</name>
    <description type="text">Testsuite has testcases with many steps
    and
many lines in description</description>
    <test-cases>
        <test-case start="1412949539800" stop="1412949540461" status="failed">
            <name>longAssertionTest</name>
            <title>Test with long assertion text</title>
            <failure>
                <message>AssertionError: 
Expected: "{\n\"name\": \"test\",\n\"value\": \"ok value\"\n}"
     but: was "{\n\"name\": \"test\",\n\"value\": \"bad value\"\n}"</message>
                <stack-trace>java.lang.AssertionError: 
Expected: "{\n\"name\": \"test\",\n\"value\": \"ok value\"\n}"
     but: was "{\n\"name\": \"test\",\n\"value\": \"bad value\"\n}"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at my.company.ManyInfoTest.longAssertionTest(ManyInfoTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
</stack-trace>
            </failure>
            <steps/>
            <attachments>
                <attachment title="System Environment" source="6daa25ef-f800-4f13-bbf5-0e67375d2918-attachment.txt" type="text/plain" size="18356"/>
            </attachments>
            <labels>
                <label name="severity" value="normal"/>
                <label name="host" value="my.cool.host.com"/>
                <label name="thread" value="pool-1-thread-6"/>
                <label name="issue" value="JIRA-1"/>
                <label name="issue" value="JIRA-2"/>
                <label name="testId" value="TMS-1"/>
            </labels>
            <parameters>
                <parameter name="PATH" value="/Users/charlie/.rvm/gems/ruby-2.0.0-p481/bin:/Users/charlie/.rvm/gems/ruby-2.0.0-p481@global/bin:/Users/charlie/.rvm/rubies/ruby-2.0.0-p481/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/usr/local/MacGPG2/bin:/usr/texbin:/usr/local/Cellar/maven/3.0.5/libexec/bin:/Library/Java/JavaVirtualMachines/jdk1.7.0_21.jdk/Contents/Home/bin:/Users/charlie/.rvm/bin" kind="environment-variable"/>
                <parameter name="BASEDIR" value="/Users/charlie/IdeaProjects/allure-junit-variant" kind="environment-variable"/>
                <parameter name="OS_NAME" value="Mac OS X" kind="environment-variable"/>
                <parameter name="OS_VERSION" value="10.9.4" kind="environment-variable"/>
                <parameter name="JAVA_VERSION" value="1.7.0_21" kind="environment-variable"/>
            </parameters>
        </test-case>
        <test-case start="1412949439801" stop="1412949540559" status="failed">
            <name>attachmentsTest</name>
            <title>&lt;script&gt;3443&lt;/script&gt;</title>
            <description type="text">Single-line description</description>
            <failure>
                <message>AlarmAssertionErrorAssertionErrorAssertionErrorAssertionErrorAssertionError: This test should be failed</message>
                <stack-trace>java.lang.AssertionError: This test should be failed
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at my.company.steps.CommonSteps.makeThisTestFailed(CommonSteps.java:37)
	at my.company.ManyInfoTest.attachmentsTest(ManyInfoTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
</stack-trace>
            </failure>
            <steps>
                <step start="1412949540546" stop="1412949540559" status="failed">
                    <name>makeThisTestFailed</name>
                    <title>Make this test failed</title>
                    <attachments>
                        <attachment title="TXT Attachment" source="01261e59-9b21-408d-9dff-34daec2addff-attachment.txt" type="text/plain"/>
                    </attachments>
                </step>
            </steps>
            <attachments>
                <attachment title="JSON Attachment" source="51aee409-51ce-44ee-a8c0-82e5a3c4fdad-attachment.json" type="application/json"/>
                <attachment title="XML Attachment" source="8bc0e8b2-b9f3-4d94-ae5e-99540156e65e-attachment.xml" type="application/xml"/>
                <attachment title="JPG Attachment" source="8e86c8ae-c2cd-49d4-a1b8-87592aa6de02-attachment.png" type="image/png"/>
                <attachment title="CSV Attachment" source="b81da3c0-1b9d-4219-9e35-87e139ec446c-attachment.csv" type="text/csv"/>
            </attachments>
            <labels>
                <label name="severity" value="critical"/>
                <label name="story" value="OtherScreenshot"/>
                <label name="feature" value="Screenshot"/>
                <label name="host" value="my.cool.host.com"/>
                <label name="thread" value="pool-1-thread-5"/>
                <label name="issue" value="JIRA-1"/>
                <label name="issue" value="JIRA-2"/>
                <label name="testId" value="TMS-1"/>
            </labels>
        </test-case>
        <test-case start="1412949539794" stop="1412949540559" status="failed">
            <name>attachmentsTest</name>
            <title>&lt;script&gt;3443&lt;/script&gt;</title>
            <description type="text">Single-line description</description>
            <failure>
                <message>AlarmAssertionErrorAssertionErrorAssertionErrorAssertionErrorAssertionError: This test should be failed</message>
                <stack-trace>java.lang.AssertionError: This test should be failed
                    at org.junit.Assert.fail(Assert.java:88)
                    at org.junit.Assert.assertTrue(Assert.java:41)
                    at my.company.steps.CommonSteps.makeThisTestFailed(CommonSteps.java:37)
                    at my.company.ManyInfoTest.attachmentsTest(ManyInfoTest.java:35)
                    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
                    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                    at java.lang.reflect.Method.invoke(Method.java:601)
                    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
                    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
                    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
                    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
                    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
                    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
                    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
                    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
                    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
                    at java.lang.Thread.run(Thread.java:722)
                </stack-trace>
            </failure>
            <steps>
                <step start="1412949540546" stop="1412949540559" status="failed">
                    <name>makeThisTestFailed</name>
                    <title>Make this test failed</title>
                    <attachments>
                        <attachment title="TXT Attachment" source="01261e59-9b21-408d-9dff-34daec2addff-attachment.txt" type="text/plain"/>
                    </attachments>
                </step>
            </steps>
            <attachments>
                <attachment title="JSON Attachment" source="51aee409-51ce-44ee-a8c0-82e5a3c4fdad-attachment.json" type="application/json"/>
                <attachment title="XML Attachment" source="8bc0e8b2-b9f3-4d94-ae5e-99540156e65e-attachment.xml" type="application/xml"/>
                <attachment title="JPG Attachment" source="8e86c8ae-c2cd-49d4-a1b8-87592aa6de02-attachment.png" type="image/png"/>
                <attachment title="CSV Attachment" source="b81da3c0-1b9d-4219-9e35-87e139ec446c-attachment.csv" type="text/csv"/>
            </attachments>
            <labels>
                <label name="severity" value="critical"/>
                <label name="story" value="OtherScreenshot"/>
                <label name="feature" value="Screenshot"/>
                <label name="host" value="my.cool.host.com"/>
                <label name="thread" value="pool-1-thread-5"/>
                <label name="issue" value="JIRA-1"/>
                <label name="issue" value="JIRA-2"/>
                <label name="testId" value="TMS-1"/>
            </labels>
        </test-case>
        <test-case start="1412949529800" stop="1412949540559" status="failed">
            <name>attachmentsTest</name>
            <title>&lt;script&gt;3443&lt;/script&gt;</title>
            <description type="text">Single-line description</description>
            <failure>
                <message>AlarmAssertionErrorAssertionErrorAssertionErrorAssertionErrorAssertionError: This test should be failed</message>
                <stack-trace>java.lang.AssertionError: This test should be failed
                    at org.junit.Assert.fail(Assert.java:88)
                    at org.junit.Assert.assertTrue(Assert.java:41)
                    at my.company.steps.CommonSteps.makeThisTestFailed(CommonSteps.java:37)
                    at my.company.ManyInfoTest.attachmentsTest(ManyInfoTest.java:35)
                    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
                    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                    at java.lang.reflect.Method.invoke(Method.java:601)
                    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
                    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
                    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
                    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
                    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
                    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
                    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
                    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
                    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
                    at java.lang.Thread.run(Thread.java:722)
                </stack-trace>
            </failure>
            <steps>
                <step start="1412949540546" stop="1412949540559" status="failed">
                    <name>makeThisTestFailed</name>
                    <title>Make this test failed</title>
                    <attachments>
                        <attachment title="TXT Attachment" source="01261e59-9b21-408d-9dff-34daec2addff-attachment.txt" type="text/plain"/>
                    </attachments>
                </step>
            </steps>
            <attachments>
                <attachment title="JSON Attachment" source="51aee409-51ce-44ee-a8c0-82e5a3c4fdad-attachment.json" type="application/json"/>
                <attachment title="XML Attachment" source="8bc0e8b2-b9f3-4d94-ae5e-99540156e65e-attachment.xml" type="application/xml"/>
                <attachment title="JPG Attachment" source="8e86c8ae-c2cd-49d4-a1b8-87592aa6de02-attachment.png" type="image/png"/>
                <attachment title="CSV Attachment" source="b81da3c0-1b9d-4219-9e35-87e139ec446c-attachment.csv" type="text/csv"/>
            </attachments>
            <labels>
                <label name="severity" value="critical"/>
                <label name="story" value="OtherScreenshot"/>
                <label name="feature" value="Screenshot"/>
                <label name="host" value="my.cool.host.com"/>
                <label name="thread" value="pool-1-thread-5"/>
                <label name="issue" value="JIRA-1"/>
                <label name="issue" value="JIRA-2"/>
                <label name="testId" value="TMS-1"/>
            </labels>
        </test-case>
        <test-case start="1412949539801" stop="1412949539862" status="broken">
            <name>lotOfStepsTest</name>
            <description type="text">I have many steps 

    Parent Step 
    Last 
    MakeThisTestBroken</description>
            <failure>
                <message>FileNotFoundException: No file found.</message>
                <stack-trace>java.io.FileNotFoundException: No file found.
	at my.company.steps.CommonSteps.makeThisTestBroken(CommonSteps.java:31)
	at my.company.ManyInfoTest.lotOfStepsTest(ManyInfoTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
</stack-trace>
            </failure>
            <steps>
                <step start="1412949539854" stop="1412949539857" status="passed">
                    <name>parentStep</name>
                    <title>Parent step</title>
                    <steps>
                        <step start="1412949539854" stop="1412949539857" status="passed">
                            <name>step[First nested]</name>
                            <title>"First nested" step</title>
                        </step>
                        <step start="1412949539857" stop="1412949539857" status="passed">
                            <name>step[Second nested]</name>
                            <title>"Second nested" step</title>
                        </step>
                        <step start="1412949539857" stop="1412949539857" status="passed">
                            <name>step[Third nested]</name>
                            <title>"Third nested" step</title>
                        </step>
                    </steps>
                </step>
                <step start="1412949539858" stop="1412949539858" status="passed">
                    <name>step[Last]</name>
                    <title>"Last" step</title>
                </step>
                <step start="1412949539859" stop="1412949539860" status="passed">
                    <name>veryLongStep</name>
                    <title>
                        Very long step with many info. Very long step with many info. Very long step with many info.
                    </title>
                </step>
                <step start="1412949539858" stop="1412949539862" status="broken">
                    <name>makeThisTestBroken</name>
                    <title>Make this test broken</title>
                </step>
            </steps>
            <attachments/>
            <labels>
                <label name="severity" value="blocker"/>
                <label name="host" value="my.cool.host.com"/>
                <label name="thread" value="pool-1-thread-7"/>
                <label name="testId" value="TMS-1"/>
            </labels>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="JUnit"/>
        <label name="language" value="JAVA"/>
        <label name="status_details" value="flaky"/>
    </labels>
</ns2:test-suite>
